version: '3'

networks:
  web:
    external: true
  internal:
    external: false

services:
  web:
    build: .
    container_name: web
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; gunicorn --bind 0.0.0.0:8000 config.wsgi'
    volumes:
      - .:/home/user/web
    restart: always
    ports:
      - '8010:8000'
    expose:
      - 8010
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.django.rule=Host(`$DOMAIN_NAME`)"
      #- "traefik.http.routers.django.tls=true"
      ## HTTP Routers
      - "traefik.http.routers.django-rtr.entrypoints=https"
      - "traefik.http.routers.django-rtr.rule=Host(`$DOMAIN_NAME`)"
      ## Middlewares
      - "traefik.http.routers.django-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.django-rtr.service=django-svc"
      - "traefik.http.services.django-svc.loadbalancer.server.port=8000"
      ## Disable from watchtower
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - web
      - internal

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    env_file:
      - .env
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/static:/static
      - ./config/media:/media
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.static-http.entrypoints=https"      
      - "traefik.http.routers.static-http.rule=Host(`${DOMAIN_NAME}`) && PathPrefix(`/static`,`/media`)"
    networks:
      - web
      - internal
    depends_on:
      - web
